services:

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - pedidos
      - inventario
      - pagos

  pedidos:
    build: ./pedidos

  inventario:
    build: ./inventario

  pagos:
    build: ./pagos