services:

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - usuarios
      - turnos
      - historial
      - notificaciones
    restart: always

  usuarios:
    build: ./usuarios
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  turnos:
    build: ./turnos
    ports:
      - "5002:5000"
    env_file:
      - .env
    depends_on:
      - db
      - notificaciones
      - historial
    restart: always

  notificaciones:
    build: ./notificaciones
    ports:
      - "5003:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  historial:
    build: ./historial
    ports:
      - "5004:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: