services:

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - usuarios
      - turnos
      - historial
      - notificaciones
    restart: always

  usuarios:
    build: ./usuarios
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db_usuarios
    restart: always

  turnos:
    build: ./turnos
    ports:
      - "5002:5000"
    env_file:
      - .env
    depends_on:
      - db_turnos
      - notificaciones
      - historial
    restart: always

  historial:
    build: ./historial
    ports:
      - "5003:5000"
    env_file:
      - .env
    depends_on:
      - db_historial
    restart: always

  notificaciones:
    build: ./notificaciones
    ports:
      - "5004:5000"
    env_file:
      - .env
    depends_on:
      - db_notificaciones
    restart: always

  db_usuarios:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USUARIOS_DB_NAME}
    volumes:
      - usuarios_data:/var/lib/mysql
    restart: always

  db_turnos:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TURNOS_DB_NAME}
    volumes:
      - turnos_data:/var/lib/mysql
    restart: always

  db_historial:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${HISTORIAL_DB_NAME}
    volumes:
      - historial_data:/var/lib/mysql
    restart: always

  db_notificaciones:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NOTIFICACIONES_DB_NAME}
    volumes:
      - notificaciones_data:/var/lib/mysql
    restart: always

volumes:
  usuarios_data:
  turnos_data:
  historial_data:
  notificaciones_data: